---
title: "Common Garden Analyses"
author: "Vicki M. Zhang"
date: "January 22, 20252024"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

# Setting up

## Packages

```{r include=FALSE}
library(here)
library(devtools)
library(tidyverse)
library(lubridate)
library(car)
library(ggmap)
library(ggstar)
library(ggrepel)
library(ggsn)
library(ggpubr)
library(rnaturalearth)
library(drcte)
library(lme4)
library(lmerTest)
library(MuMIn)
library(emmeans)
library(multcomp)
library(patchwork)
```

## Data

```{r import data}
comgar_df <- read_csv(here("4.1_Soil_Origin/data/commongarden_df.csv"))
```

### Wrangling data

```{r}
df_comgar <- comgar_df %>% 
  # change classes to factor
  mutate_at(c("plot", "soil", "species"), as.factor) %>% 
  
  # change flowering21 to logical
  mutate(flowering21 = as.logical(ifelse(flowering21 == "Y", 1, 0))) %>% 
  
  # change class of survival & performance to numeric
  mutate_at(c(5:8, 10:27, 29:39), as.numeric) %>% 
  
  # change biomass to mg
  mutate(biomass_a24 = biomass_a24 * 1000,
         biomass_b24 = biomass_b24 * 1000, 
         biomass24 = biomass24 * 1000) %>% 
  
  # relevel treatment factor
  mutate(soil = factor(soil, levels = c("dump", "tundra")))

# check
# str(df_comgar)
```

```{r survival}
df_survival <- df_comgar %>% 
  pivot_longer(cols = c(survival21, survival22, survival23, survival24),
               names_to = "year_survival",
               names_prefix = "survival",
               values_to = "survival") %>% 
  pivot_longer(cols = c(dead21, dead22, dead23, dead24),
               names_to = "year_dead",
               names_prefix = "dead",
               values_to = "dead") %>% 
  dplyr::select(c(plot, soil, species, year_survival, survival, year_dead, dead)) %>% 
  # remove duplicate years
  filter(year_survival == year_dead) %>% 
  mutate_at(c("year_survival", "year_dead"),
            as.integer) %>% 
  mutate("year_survivalf" = as.factor(year_survival))
```

```{r performance long}
df_performance <- df_comgar %>%
  dplyr::select(soil, plot, species,
                height21, leaflength21, 
                ramets22, height22, leaflength22, numleaves22, numflower22,
                ramets23, height23, leaflength23, numleaves23, numflower23,
                ramets24, height24, leaflength24, numleaves24, numflower24,
                biomass_a24, biomass_b24, biomass24) %>% 
  pivot_longer(cols = -c(plot, soil, species),
               names_to = c("performance", "year"),
               names_pattern = "([a-z]+)([0-9]+)",
               values_to = "values") %>% 
  mutate_at("year", as.integer) %>% 
  mutate("year_f" = as.factor(year))

df_performance_init <- df_comgar %>%
  dplyr::select(soil, plot, species,
                height21, leaflength21, 
                ramets22, height22, leaflength22, numleaves22, numflower22,
                ramets23, height23, leaflength23, numleaves23, numflower23,
                ramets24, height24, leaflength24, numleaves24, numflower24,
                biomass_a24, biomass_b24, biomass24) %>% 
  pivot_longer(cols = -c(plot, soil, species,
                         height21, leaflength21), # initial measurements kept in separate column
               names_to = c("performance", "year"),
               names_pattern = "([a-z]+)([0-9]+)",
               values_to = "values") %>% 
  mutate_at("year", as.integer) %>% 
  mutate("year_f" = as.factor(year))

df_lvul_performance <- df_performance_init %>% 
  filter(species == "Lvul")

df_pmaj_performance <- df_performance_init %>% 
  filter(species == "Pmaj")

df_toff_performance <- df_performance_init %>% 
  filter(species == "Toff")
```

# Map

```{r churchill on canada map}
churchill <- data.frame(longitude = c(-94.1650), latitude = c(58.7684))

map_insetcanada <- map_data("world", region = "canada") %>% 
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group),
               fill = "white", colour = "black") +
  geom_star(data = churchill,
            aes(x = longitude , y = latitude),
            size = 3,
            fill = "black") +
  theme(line = element_blank(),
        axis.title = element_blank(),
        axis.text  = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA),
        plot.background = element_blank())

map_insetcanada

# ggsave(here::here("4.1_Soil_Origin/plots/map_insetcanada.png"), map_insetcanada,
#        width = 8, height = 6)
```

```{r common garden coordinates}
# 8 unique plots
comgar_coords <- data.frame(longitude = c(-93.79056), latitude = c(58.73472))
```

```{r ggmap comgar coordinates}
map_churchill <- get_map(location = "Churchill Northern Studies Centre, MB, Canada",
                         zoom = 12,
                         maptype = "roadmap",
                         color = "color", force = TRUE)

map_mainchurchill <- ggmap(map_churchill) +
  geom_point(data = comgar_coords,
             aes(x = longitude, y = latitude),
            size = 2) +
  scalebar(location = "bottomright",
           x.min = -93.80, x.max = -93.73,
           y.min = 58.69, y.max = 58.73,
           dist = 2, dist_unit = "km",
           transform = TRUE, model = 'WGS84',
           st.dist = 0.05, st.size = 3,
           border.size = 0.5) +
  labs(y = "Longitude", x = "Latitude") +
  theme(panel.border = element_rect(colour = "black", fill=NA))

map_mainchurchill

# ggsave(here::here("4.1_Soil_Origin/plots/map_mainchurchill.png"), map_mainchurchill,
#        width = 8, height = 6)
```

```{r inset and main}
map_final <- map_mainchurchill +
  inset(ggplotGrob(map_insetcanada),
        xmin = -93.93, xmax = -93.83,
        ymin = 58.75, ymax = 58.795)
map_final

# ggsave(here::here("4.1_Soil_Origin/plots/map_final.png"), map_final,
#        width = 8, height = 6)
```

# Initial Data

*Check if needed.*

## T-test

```{r}
wilcox.test(height21 ~ soil, data = df_comgar) 
wilcox.test(leaflength21 ~ soil, data = df_comgar[df_comgar$species == "Pmaj", ]) 
wilcox.test(leaflength21 ~ soil, data = df_comgar[df_comgar$species == "Toff", ])
```

## Figures

```{r boxplot}
fig_leafln <- ggplot(data = df_comgar, aes(x = species, y = leaflength21,
                             fill = soil)) +
  scale_fill_brewer(palette = "Set1",
                    name = "Soil type", labels = c("Dumped", "Original")) +
  scale_x_discrete(labels = c("L. vularis", "P. major", "T. officinale")) +
  labs(x = "Species", y = "Intial Leaf length (cm)") +
  geom_boxplot() +
  theme_vz() +
  theme(axis.text.x = element_text(face = "italic"))

fig_leafln
```

```{r histogram}
ggplot(data = df_comgar, aes(x = leaflength21)) +
  geom_histogram() +
  facet_wrap(~ species)
```

```{r data assumptions}
# normality
shapiro.test(subset(df_comgar, species == "Lvul")$height21)

shapiro.test(subset(df_comgar, species == "Pmaj")$leaflength21)

shapiro.test(subset(df_comgar, species == "Toff")$leaflength21)

# variance
bartlett.test(leaflength21 ~ species, data = df_comgar) 
bartlett.test(leaflength21 ~ interaction(species, soil),
              data = df_comgar)

leveneTest(leaflength21 ~ species, data = df_comgar)
leveneTest(leaflength21 ~ soil, data = df_comgar)

leveneTest(leaflength21 ~ species*soil, data = df_comgar)
# variances of leaf length between plots had equal variances

# apply(df_transplant, 2 ,shapiro.test)
```

# Survival

```{r survival per species summary}
survival_sum <- df_comgar %>% 
  pivot_longer(cols = c(survival21, survival22, survival23, survival24),
               names_to = "status",
               values_to = "survival") %>% 
  separate_wider_position(cols = "status",
                          widths = c(status = 8, year = 2))%>% 
  group_by(species, soil, year) %>%  
  dplyr::summarise(alive = sum(survival == 1, na.rm = TRUE),
                   dead = sum(survival == 0, na.rm = TRUE),
                   propsurvival = alive/(alive + dead),
                   sd = sd(survival),
                   se = sd/sqrt(alive))

# annual deaths
df_survival %>% 
  group_by(species, soil, year_survival, year_dead) %>% 
  dplyr::summarise(alive = sum(survival == 1, na.rm = TRUE),
                   dead = sum(dead == 1, na.rm = TRUE),
                   propsurvival = alive/(alive + dead))
  
```

```{r total survival per species}
fig_sppsurvival <- survival_sum %>%
  ggplot(aes(x = year, y = propsurvival, colour = species, shape = soil,
             group = interaction(soil, species))) +
  geom_line(aes(linetype = soil),
            # colour = "grey",
            position = position_dodge(0.2)) +
  geom_point(size = 3,
            position = position_dodge(0.2))  +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_y_continuous(name = "Proportion of surviving transplants") +
  scale_colour_brewer(palette = "Dark2",
                      name = "Species",
                      labels = c(expression(italic("L. vulgaris")),
                                 expression(italic("P. major")),
                                 expression(italic("T. officinale")))) +
  scale_linetype(name = "Soil Origin",
                 labels = c("Dump", "Tundra (Control)")) +
  scale_shape_manual(name = "Soil Origin",
                     labels = c("Dump", "Tundra (Control)"),
                     values = c(17, 16)) +
  theme_vz() +
  # theme_darkclassic() +
  theme(legend.text.align = 0,
        # legend.position = "none"
        )

# ggsave(here::here("4.1_Soil_Origin/plots/fig_sppsurvival.png"), fig_sppsurvival,
#        width = 12, height = 7)
```

# Biomass

```{r}
df_performance %>% 
  group_by(species, soil, year) %>%
  filter(performance == "biomass" & !is.na(values))
```


```{r}
fig_sppbiomass <- df_performance %>% 
  group_by(species, soil, year) %>%
  filter(performance == "biomass") %>% 
  dplyr::summarise(mean = mean(values, na.rm = TRUE),
                   n = n(),
                   sd = sd(values, na.rm = TRUE),
                   se = sd/sqrt(n)) %>% 
  ggplot(aes(x = species, y = mean,
             fill = soil)) +
  geom_col(aes(fill = soil), position = position_dodge2(preserve = "single"),
           colour = "black") +
  geom_errorbar(aes(x = species, ymin = mean - se, ymax = mean + se),
                position = position_dodge2(padding = 0.5, preserve = "single"),
                colour = "black") +
  scale_fill_brewer(name = "Soil Origin",
                    palette = "BrBG", direction = 1,
                    labels = c("Dump", "Tundra (Control)")) +
  scale_x_discrete(name = "Species",
                   labels = c("L. vulgaris", "P. major", "T. officinale")) + 
  scale_y_continuous(name = "Mean biomass (mg)",
                     expand = c(0, 0), limits = c(0, 150)) +
  theme_vz() +
  # theme_darkclassic() +
  theme(axis.text.x = element_text(face = "italic"), 
        legend.position = "right")

# ggsave(here::here("4.1_Soil_Origin/plots/fig_sppbiomass.png"), fig_sppbiomass,
#        width = 12, height = 7)
```

# Individual Species Survival & Performance

## *L. vulgaris*

### Survival

```{r total survival}
# figure
fig_lvultotalsurvival <- survival_sum %>% 
  group_by(soil) %>% 
  filter(species == "Lvul") %>% 
  
  # plot
  ggplot(aes(x = year,
             y = propsurvival,
             fill = soil)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = paste("n =", alive)),
            position = position_dodge(0.9),
            vjust = -0.5) +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_y_continuous(name = "Total number of surviving transplants") +
  scale_fill_brewer(name = "Soil Origin",
                    palette = "Accent",
                    labels = c("Dump", "Tundra (Control)")) +
  theme_vz()

# ggsave(here::here("4.1_Soil_Origin/plots/fig_lvultotalsurvival.png"), fig_lvultotalsurvival,
#        width = 12, height = 7)
```


#### GLM

```{r}
# glm
survival_fixed <- glm(survival ~ soil * year_survivalf,
                      family = binomial(),
                      data = df_survival[df_survival$species == "Lvul", ],
                      subset = year_survivalf != "21")

survival_fixed1 <- glm(survival ~ soil + year_survivalf,
                      family = binomial(),
                      data = df_survival[df_survival$species == "Lvul", ],
                      subset = year_survivalf != "21")

summary(survival_fixed)
Anova(survival_fixed, p.adjust.method = TRUE, type = "3", test.statistic = "Wald")

survival_mixed <- glmer(survival ~ soil + year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Lvul", ],
                        subset = year_survivalf != "21")

survival_mixed1 <- glmer(survival ~ soil * year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Lvul",],
                        subset = year_survivalf != "21")

survival_mixed2 <- glmer(survival ~ soil + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Lvul", ],
                        subset = year_survivalf != "21")


# model comparison
AICc(survival_fixed, survival_fixed1, survival_mixed, survival_mixed1, survival_mixed2)
```


```{r}
survival_mixed <- glmer(survival ~ soil + year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Lvul", ],
                        subset = year_survivalf != "21")

summary(survival_mixed)
Anova(survival_mixed, type = "3", p.adjust.methods = TRUE, test.statistic = "Chisq")

# post-hoc
surv_pairs <- emmeans(survival_mixed, ~ soil + year_survivalf,
                      type = "response")

summary(surv_pairs)
cld(surv_pairs, Letters = letters)

pairs(surv_pairs, adjust = "tukey", reverse = "TRUE")
```

### Performance

```{r normality}
# normality of height
shapiro.test(df_lvul_performance[df_lvul_performance$performance == "height", ]$values)
hist(df_lvul_performance[df_lvul_performance$performance == "height", ]$values)

# normality of ramets
shapiro.test(df_lvul_performance[df_lvul_performance$performance == "ramets", ]$values)
hist(df_lvul_performance[df_lvul_performance$performance == "ramets", ]$values)
```

```{r transformation}
df_lvul_performance$values_transformed <- log(df_lvul_performance$values)
```

```{r Lvul performance summary}
lvul_perf_sum <- df_performance %>% 
  filter(species == "Lvul" & (performance == "height" | performance == "ramets")) %>% 
  group_by(soil, year_f, performance) %>% 
  summarize(mean = mean(values, na.rm = TRUE),
            n = n(),
            sd = sd(values, na.rm = TRUE),
            se = sd/sqrt(n), na.rm = TRUE) %>%
  mutate(mean = replace_na(mean, 0),
         se = replace_na(se, 0))
```


```{r average height and ramets boxplot}
lvul_perf_sum %>% 
  filter(performance == "height" | 
           performance == "ramets") %>% 
  ggplot(aes(x = year_f, y = mean, fill = soil)) +
  geom_boxplot(position = position_dodge2(preserve = "single")) +
  facet_wrap(~ performance) +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_fill_brewer(name = "Habitat",
                    palette = "Accent",
                    labels = c("Dump", "Tundra (Control)")) +
  theme_vz()
```

#### LM 
```{r height models}
# lm
lvul_fixed1 <- lm(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                 values_transformed ~ soil * year_f + height21)

lvul_fixed <- lm(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                 values_transformed ~ soil + year_f + height21)

# lmer
lvul_mixed <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                   values_transformed ~ soil + year_f + (1|plot),
                   REML = F)

lvul_mixed1 <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                   values_transformed ~ soil * year_f + (1|plot),
                   REML = F)

lvul_mixed2 <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                   values_transformed ~ soil * year_f + height21 + (1|plot),
                   REML = F)

lvul_mixed3 <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                   values_transformed ~ soil + year_f + height21 + (1|plot),
                   REML = F)

# model comparison
AICc(lvul_fixed, lvul_fixed1, lvul_mixed, lvul_mixed1, lvul_mixed2, lvul_mixed3)
```

```{r}
# final model
lvul_mixed <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "height", ],
                   values_transformed ~ soil + year_f + (1|plot),
                   REML = T)

# normality
qqnorm(residuals(lvul_mixed))
qqline(residuals(lvul_mixed))

shapiro.test(residuals(lvul_mixed))

# coefficients
summary(lvul_mixed)
Anova(lvul_mixed, p.adjust.method = TRUE, type = "3", test.statistic = "F")

# r2
r.squaredGLMM(lvul_mixed)

# post-hoc
lvul_emmeans <- emmeans(lvul_mixed, ~ soil + year_f, type = "response")

summary(lvul_emmeans)
lvul_emmeans1 <- cld(lvul_emmeans, Letters = letters) # significance letters

pairs(lvul_emmeans, adjust = "tukey")
```

```{r ramets models}
# lm
lvul_fixed <- lm(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                 values ~ soil * year_f + height21)

lvul_fixed1 <- lm(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                 values ~ soil + year_f + height21)

# lmer
lvul_mixed <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                   values ~ soil + year_f + (1|plot),
                   REML = F)

lvul_mixed1 <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                   values ~ soil * year_f + (1|plot),
                   REML = F)

lvul_mixed2 <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                   values ~ soil * year_f + height21 + (1|plot),
                   REML = F)

lvul_mixed3 <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                   values ~ soil + year_f + height21 + (1|plot),
                   REML = F)

# comparison
AICc(lvul_fixed, lvul_fixed1, lvul_mixed, lvul_mixed1, lvul_mixed2, lvul_mixed3)
```

```{r}
# final model
lvul_mixed <- lmer(data = df_lvul_performance[df_lvul_performance$performance == "ramets", ],
                   values ~ soil + year_f + (1|plot),
                   REML = T)

# normality
qqnorm(residuals(lvul_mixed))
qqline(residuals(lvul_mixed))

shapiro.test(residuals(lvul_mixed))

# coefficients
summary(lvul_mixed)
Anova(lvul_mixed, p.adjust.method = TRUE, type = "3", test.statistic = "F")

# r2
r.squaredGLMM(lvul_mixed)

# post-hoc
lvul_emmeans <- emmeans(lvul_mixed, ~ soil + year_f, type = "response")

summary(lvul_emmeans)
lvul_emmeans2 <- cld(lvul_emmeans, Letters = letters) # significance letters

pairs(lvul_emmeans, adjust = "tukey")
```

#### Figure

```{r Lvul performance plot}
# add performance labels
lvul_emmeans1$performance <- "height"
lvul_emmeans2$performance <- "ramets"

# bind emmeans of performance measurements
lvul_emmeans <- rbind(lvul_emmeans1, lvul_emmeans2)

# bind to summary
emm_df <- full_join(lvul_perf_sum[lvul_perf_sum$year_f != 21, ],
                    lvul_emmeans,
                    by = c("soil", "year_f", "performance"))

# remove measurements that are 0
emm_df <- emm_df %>% 
  mutate(group = ifelse(mean == 0, "", .group)) %>% 
  dplyr::select(-.group)

# figure
fig_lvulperf <- lvul_perf_sum %>% 
  filter(performance == "height" | performance == "ramets") %>% 
  ggplot(aes(x = year_f, y = mean)) +
  geom_col(aes(fill = soil), colour = "black",
           position = position_dodge2(preserve = "single")) +
  facet_wrap(~ performance,
             labeller = as_labeller(c("height" = "Mean height (cm)",
                                      "ramets" = "Mean number of ramets")),
             scales = "free_y",
             strip.position = "left") +
  geom_errorbar(aes(x = year_f, ymin = ifelse(mean - se < 0, 0, mean - se), ymax = mean + se),
                position = position_dodge2(padding = 0.5),
                colour = "black") +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_y_continuous(name = NULL,
                     limits = c(0, NA), expand = expansion(mult = c(0, 0.2))) + 
  scale_fill_brewer(name = "Soil Origin",
                    palette = "BrBG", direction = 1,
                    labels = c("Dump", "Tundra (Control)")) +
  geom_text(data = emm_df,
            aes(y = mean + se, label = group,
                vjust = -1),
            position = position_dodge2(width = 0.9)) +
  theme_vz() +
  # theme_darkclassic() +
  theme(strip.background = element_blank(),
        strip.placement = "outside",
        legend.position = "none")

# ggsave(here::here("4.1_Soil_Origin/plots/fig_lvulperf.png"), fig_lvulperf,
#        width = 12, height = 7)
```


## *P. major*

### Survival

```{r total survival}
fig_pmajtotalsurvival <- survival_sum %>% 
  group_by(soil) %>% 
  filter(species == "Pmaj") %>% 
  
  # plot
  ggplot(aes(x = year,
             y = propsurvival,
             fill = soil)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = paste("n =", alive)),
            position = position_dodge(0.9),
            vjust = -0.5) +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_y_continuous(name = "Total number of surviving transplants") +
  scale_fill_brewer(name = "Soil Origin",
                    palette = "Accent",
                    labels = c("Dump", "Tundra (Control)")) +
  theme_vz()

# ggsave(here::here("4.1_Soil_Origin/plots/fig_pmajtotalsurvival.png"), fig_pmajtotalsurvival,
#        width = 12, height = 7)
```

#### GLM

```{r survival habitat*year}
# glm
survival_fixed <- glm(survival ~ soil * year_survivalf,
                      family = binomial(),
                      data = df_survival[df_survival$species == "Pmaj", ],
                      subset = year_survivalf != "21")

survival_fixed1 <- glm(survival ~ soil + year_survivalf,
                      family = binomial(),
                      data = df_survival[df_survival$species == "Pmaj", ],
                      subset = year_survivalf != "21")

summary(survival_fixed)
Anova(survival_fixed, p.adjust.method = TRUE, type = "3", test.statistic = "Wald")

survival_mixed <- glmer(survival ~ soil + year_survivalf + (1 | plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Pmaj",],
                        subset = year_survivalf != "21")

survival_mixed1 <- glmer(survival ~ soil * year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Pmaj", ],
                        subset = year_survivalf != "21")

survival_mixed2 <- glmer(survival ~ soil + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Pmaj", ],
                        subset = year_survivalf != "21")

# model comparison
AICc(survival_fixed, survival_fixed1, survival_mixed, survival_mixed1, survival_mixed2)
```

```{r}
survival_mixed <- glmer(survival ~ soil + year_survivalf + (1 | plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Pmaj",],
                        subset = year_survivalf != "21")

summary(survival_mixed)
Anova(survival_mixed, type = "3", p.adjust.methods = TRUE, test.statistic = "Chisq")


# post-hoc
surv_pairs <- emmeans(survival_mixed, ~ soil + year_survivalf,
                      type = "response")
summary(surv_pairs)
cld(surv_pairs, Letters = letters)

pairs(surv_pairs, adjust = "tukey", reverse = "TRUE")
```

### Performance

```{r normality}
# normality of height
shapiro.test(df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ]$values)
hist(df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ]$values)

# normality of ramets
shapiro.test(df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ]$values)
hist(df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ]$values)
```

```{r transformation}
df_pmaj_performance$values_transformed <- log(df_pmaj_performance$values)
```

```{r Pmaj performance summary}
pmaj_perf_sum <- df_performance %>% 
  filter(species == "Pmaj" & (performance == "leaflength" | performance == "numleaves")) %>% 
  group_by(soil, year_f, performance) %>% 
  summarize(mean = mean(values, na.rm = TRUE),
            n = n(),
            sd = sd(values, na.rm = TRUE),
            se = sd/sqrt(n), na.rm = TRUE) %>%
  mutate(mean = replace_na(mean, 0),
         se = replace_na(se, 0))
```

```{r Pmaj average leaf length and number boxplot}
df_pmaj_performance %>% 
  filter(performance == "leaflength" |
           performance == "numleaves") %>% 
  ggplot(aes(x = year_f, y = values, fill = soil)) +
  geom_boxplot(position = position_dodge2(preserve = "single")) +
  facet_wrap(~ performance)  +
  # scale_x_discrete(name = "Year",
  #                  labels = c("2021", "2022", "2023", "2024")) +
  scale_fill_brewer(name = "Soil Origin",
                    palette = "Accent",
                    labels = c("Dump", "Tundra (Control)")) +
  theme_vz()
```

#### LM

```{r leaf length lm}
# lm
pmaj_fixed1 <- lm(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                 values_transformed ~ soil * year_f + leaflength21)

pmaj_fixed <- lm(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                 values_transformed ~ soil + year_f + leaflength21)

# lmer
pmaj_mixed <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                   values_transformed ~ soil + year_f + (1|plot),
                   REML = F)

pmaj_mixed1 <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                   values_transformed ~ soil * year_f + (1|plot),
                   REML = F)

pmaj_mixed2 <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                   values_transformed ~ soil * year_f + leaflength21 + (1|plot),
                   REML = F)

pmaj_mixed3 <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                   values_transformed ~ soil + year_f + leaflength21 + (1|plot),
                   REML = F)

# comparison
AICc(pmaj_fixed, pmaj_fixed1, pmaj_mixed, pmaj_mixed1, pmaj_mixed2, pmaj_mixed3)
```

```{r}
# final model
pmaj_mixed <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "leaflength", ],
                   values ~ soil + year_f + (1|plot),
                   REML = T)

# normality
qqnorm(residuals(pmaj_mixed))
qqline(residuals(pmaj_mixed))

shapiro.test(residuals(pmaj_mixed))

# coefficients
summary(pmaj_mixed)
Anova(pmaj_mixed, p.adjust.method = TRUE, type = "3", test.statistic = "F")

# r2
r.squaredGLMM(pmaj_mixed)


# post-hoc
pmaj_emmeans <- emmeans(pmaj_mixed, ~ soil + year_f, type = "response")

summary(pmaj_emmeans)
pmaj_emmeans1 <- cld(pmaj_emmeans, Letters = letters) # significance letters

pairs(pmaj_emmeans, adjust = "tukey")
```

```{r numleaves length lm}
# lm
pmaj_fixed <- lm(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                 values ~ soil * year_f + leaflength21)

pmaj_fixed1 <- lm(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                 values ~ soil + year_f + leaflength21)

# lmer
pmaj_mixed <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                   values ~ soil + year_f + (1|plot),
                   REML = F)

pmaj_mixed1 <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                   values ~ soil * year_f + (1|plot),
                   REML = F)

pmaj_mixed2 <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                   values ~ soil * year_f + leaflength21 + (1|plot),
                   REML = F)

pmaj_mixed3 <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                   values ~ soil + year_f + leaflength21 + (1|plot),
                   REML = F)

# comparison
AICc(pmaj_fixed, pmaj_fixed1, pmaj_mixed, pmaj_mixed1, pmaj_mixed2, pmaj_mixed3)
```


```{r}
# final model
pmaj_mixed <- lmer(data = df_pmaj_performance[df_pmaj_performance$performance == "numleaves", ],
                   values ~ soil + year_f + (1|plot),
                   REML = T)

# normality
qqnorm(residuals(pmaj_mixed))
qqline(residuals(pmaj_mixed))

shapiro.test(residuals(pmaj_mixed))

# coefficients
summary(pmaj_mixed)
Anova(pmaj_mixed, p.adjust.method = TRUE, type = "3", test.statistic = "F")

# r2
r.squaredGLMM(pmaj_mixed)

# post-hoc
pmaj_emmeans <- emmeans(pmaj_mixed, ~ soil + year_f, type = "response")

summary(pmaj_emmeans)
pmaj_emmeans2 <- cld(pmaj_emmeans, Letters = letters, decreasing = TRUE) # significance letters

pairs(pmaj_emmeans, adjust = "tukey")
```

#### Figure

```{r Pmaj performance plot}
# add performance labels
pmaj_emmeans1$performance <- "leaflength"
pmaj_emmeans2$performance <- "numleaves"

# bind emmeans of performance measurements
pmaj_emmeans <- rbind(pmaj_emmeans1, pmaj_emmeans2)

# bind to summary
emm_df <- full_join(pmaj_perf_sum[pmaj_perf_sum$year_f != 21, ],
          pmaj_emmeans,
          by = c("soil", "year_f", "performance"))

# remove measurements that are 0
emm_df <- emm_df %>% 
  mutate(group = ifelse(mean == 0, "", .group)) %>% 
  dplyr::select(-.group)

fig_pmajperf <- pmaj_perf_sum %>% 
  filter(performance == "leaflength" | performance == "numleaves") %>% 
  ggplot(aes(x = year_f, y = mean)) +
  geom_col(aes(fill = soil), colour = "black",
           position = position_dodge2(preserve = "single")) +
  facet_wrap(~performance,
             labeller = as_labeller(c("leaflength" = "Mean leaf length (cm)",
                                      "numleaves" = "Mean number of leaves")),
             scales = "free_y",
             strip.position = "left") +
  geom_errorbar(aes(x = year_f, ymin = ifelse(mean - se < 0, 0, mean - se), ymax = mean + se),
                position = position_dodge2(preserve = "single", padding = 0.5),
                colour = "black") +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_y_continuous(name = NULL,
                     limits = c(-0.01, NA), expand = expansion(mult = c(0, 0.2))) + 
  scale_fill_brewer(name = "Soil Origin",
                    palette = "BrBG", direction = 1,
                    labels = c("Dump", "Tundra (Control)")) +
  geom_text(data = emm_df,
            aes(y = mean + se, label = group,
                vjust = -1),
            position = position_dodge2(width = 0.9)) +
  theme_vz() +
  # theme_darkclassic() +
  theme(strip.background = element_blank(),
        strip.placement = "outside",
        legend.position = "none")

# ggsave(here::here("4.1_Soil_Origin/plots/fig_pmajperf.png"), fig_pmajperf,
#        width = 12, height = 7)
```

## *T. officinale*

### Survival

```{r total survival}
fig_tofftotalsurvival <- survival_sum %>% 
  group_by(soil) %>% 
  filter(species == "Toff") %>% 
  
  # plot
  ggplot(aes(x = year,
             y = propsurvival,
             fill = soil)) +
  geom_col(position = "dodge") +
  geom_text(aes(label = paste("n =", alive)),
            position = position_dodge(0.9),
            vjust = -0.5) +
  scale_x_discrete(name = "Year",
                   labels = c("20221", "2022", "2023", "2024")) +
  scale_y_continuous(name = "Total number of surviving transplants") +
  scale_fill_brewer(name = "Soil Origin",
                    palette = "Accent",
                    labels = c("Dump", "Tundra (Control)")) +
  theme_vz()

# ggsave(here::here("4.1_Soil_Origin/plots/fig_tofftotalsurvival.png"), fig_tofftotalsurvival,
#        width = 12, height = 7)
```

#### GLM

```{r survival habitat*year}
# glm
# year != 24 (no more surviving Toff)
survival_fixed <- glm(survival ~ soil * year_survivalf,
                      family = binomial(),
                      data = df_survival[df_survival$species == "Toff" &
                                           df_survival$year_survivalf != 24, ],
                      subset = year_survivalf != "21")

survival_fixed1 <- glm(survival ~ soil + year_survivalf,
                      family = binomial(),
                      data = df_survival[df_survival$species == "Toff" &
                                           df_survival$year_survivalf != 24, ],               
                      subset = year_survivalf != "21")

summary(survival_fixed)
Anova(survival_fixed, p.adjust.method = TRUE, type = "3", test.statistic = "Wald")

survival_mixed <- glmer(survival ~ soil + year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Toff" &
                                             df_survival$year_survivalf != 24, ],
                        control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)),
                        subset = year_survivalf != "21")

survival_mixed1 <- glmer(survival ~ soil * year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Toff" &
                                             df_survival$year_survivalf != 24, ],
                        control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)),
                        subset = year_survivalf != "21")

survival_mixed2 <- glmer(survival ~ soil + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Toff" &
                                             df_survival$year_survivalf != 24, ],
                        control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)),
                        subset = year_survivalf != "21")

# model comparison
AICc(survival_fixed, survival_fixed1, survival_mixed, survival_mixed1, survival_mixed2)
```

```{r}
survival_mixed <- glmer(survival ~ soil + year_survivalf + (1|plot),
                        family = binomial(),
                        data = df_survival[df_survival$species == "Toff" &
                                             df_survival$year_survivalf != 24, ],
                        control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)),
                        subset = year_survivalf != "21")

summary(survival_mixed)
Anova(survival_mixed, type = "3", p.adjust.methods = TRUE, test.statistic = "Chisq")

# post-hoc
surv_pairs <- emmeans(survival_fixed, ~ soil + year_survivalf,
                      type = "response")
summary(surv_pairs)
cld(surv_pairs, Letters = letters)

pairs(surv_pairs, adjust = "tukey", reverse = "TRUE")
```

### Performance

```{r normality}
# normality of height
shapiro.test(df_toff_performance[df_toff_performance$performance == "leaflength", ]$values)
hist(df_toff_performance[df_toff_performance$performance == "leaflength", ]$values)

# normality of ramets
shapiro.test(df_toff_performance[df_toff_performance$performance == "numleaves", ]$values)
hist(df_toff_performance[df_toff_performance$performance == "numleaves", ]$values)
```

```{r transformation}
df_toff_performance$values_transformed <- log(df_toff_performance$values)
```

```{r Toff performance summary}
toff_perf_sum <- df_performance %>% 
  filter(species == "Toff" & (performance == "leaflength" | performance == "numleaves")) %>% 
  group_by(soil, year_f, performance) %>% 
  summarize(mean = mean(values, na.rm = TRUE),
            n = n(),
            sd = sd(values, na.rm = TRUE),
            se = sd/sqrt(n), na.rm = TRUE) %>%
  mutate(mean = replace_na(mean, 0),
         se = replace_na(se, 0))
```

#### LM 
```{r leaf length lm}
# lm
toff_fixed <- lm(data = df_toff_performance[df_toff_performance$performance == "leaflength" &
                                              df_toff_performance$year_f != 24, ],
                 values ~ soil * year_f + leaflength21)

toff_fixed1 <- lm(data = df_toff_performance[df_toff_performance$performance == "leaflength" &
                                              df_toff_performance$year_f != 24, ],
                 values ~ soil + year_f + leaflength21)

# lmer
toff_mixed <- lmer(data = df_toff_performance[df_toff_performance$performance == "leaflength" & 
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil + year_f + (1|plot),
                   REML = F)

toff_mixed1 <- lmer(data = df_toff_performance[df_toff_performance$performance == "leaflength" &
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil * year_f + (1|plot),
                   REML = F)

toff_mixed2 <- lmer(data = df_toff_performance[df_toff_performance$performance == "leaflength" &
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil * year_f + leaflength21 + (1|plot),
                   REML = F)

toff_mixed3 <- lmer(data = df_toff_performance[df_toff_performance$performance == "leaflength" &
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil + year_f + leaflength21 + (1|plot),
                   REML = F)

# comparison
AICc(toff_fixed, toff_fixed1, toff_mixed, toff_mixed1, toff_mixed2, toff_mixed3)
```

```{r}
# final model
toff_mixed <- lmer(data = df_toff_performance[df_toff_performance$performance == "leaflength" & 
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil + year_f + (1|plot),
                   REML = T,
                   control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=2e5)))


# normality
qqnorm(residuals(toff_mixed))
qqline(residuals(toff_mixed))

shapiro.test(residuals(toff_mixed))

# coefficients
summary(toff_mixed)
Anova(toff_mixed, p.adjust.method = TRUE, type = "3", test.statistic = "F")

# r2
r.squaredGLMM(toff_mixed)


# post-hoc
toff_emmeans <- emmeans(toff_mixed, ~ soil + year_f, type = "response")

summary(toff_emmeans)
toff_emmeans1 <- cld(toff_emmeans, Letters = letters, reverse = TRUE) # significance letters

pairs(toff_emmeans, adjust = "tukey")
```

```{r number of leaves lm}
# lm
toff_fixed1 <- lm(data = df_toff_performance[df_toff_performance$performance == "numleaves" &
                                              df_toff_performance$year_f != 24, ],
                 values ~ soil * year_f + leaflength21)

toff_fixed <- lm(data = df_toff_performance[df_toff_performance$performance == "numleaves" &
                                              df_toff_performance$year_f != 24, ],
                 values ~ soil + year_f + leaflength21)

# lmer
toff_mixed1 <- lmer(data = df_toff_performance[df_toff_performance$performance == "numleaves" & 
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil + year_f + (1|plot),
                   REML = F)

toff_mixed <- lmer(data = df_toff_performance[df_toff_performance$performance == "numleaves" &
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil * year_f + (1|plot),
                   REML = F)

toff_mixed2 <- lmer(data = df_toff_performance[df_toff_performance$performance == "numleaves" &
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil * year_f + leaflength21 + (1|plot),
                   REML = F)

toff_mixed3 <- lmer(data = df_toff_performance[df_toff_performance$performance == "numleaves" &
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil + year_f + leaflength21 + (1|plot),
                   REML = F)

# comparison
AICc(toff_fixed, toff_fixed1, toff_mixed, toff_mixed1, toff_mixed2, toff_mixed3)
```

```{r}
# final model
toff_mixed <- lmer(data = df_toff_performance[df_toff_performance$performance == "numleaves" & 
                                                df_toff_performance$year_f != 24, ],
                   values ~ soil + year_f + (1|plot),
                   REML = T)


# normality
qqnorm(residuals(toff_mixed))
qqline(residuals(toff_mixed))

shapiro.test(residuals(toff_mixed))

# coefficients
summary(toff_mixed)
Anova(toff_mixed, p.adjust.method = TRUE, type = "3", test.statistic = "F")

# r2
r.squaredGLMM(toff_mixed)

# post-hoc
toff_emmeans <- emmeans(toff_mixed, ~ soil + year_f, type = "response")

summary(toff_emmeans)
toff_emmeans2 <- cld(toff_emmeans, Letters = letters, reverse = TRUE) # significance letters

pairs(toff_emmeans, adjust = "tukey")
```

#### Figure

```{r Toff performance plot}
# add performance labels
toff_emmeans1$performance <- "leaflength"
toff_emmeans2$performance <- "numleaves"

# bind emmeans of performance measurements
toff_emmeans <- rbind(toff_emmeans1, toff_emmeans2)

# significance letters are too verbose (calculating diff of means of tundra 2023)
# remove
toff_emmeans$.group <- c("a", "ab", "b", "", "a", "a", "a", "")


# bind to summary
emm_df <- full_join(toff_perf_sum[toff_perf_sum$year_f != 21, ],
          toff_emmeans,
          by = c("soil", "year_f", "performance"))

# remove measurements that are 0
emm_df <- emm_df %>% 
  mutate(group = ifelse(mean == 0, "", .group)) %>% 
  dplyr::select(-.group)

fig_toffperf <- toff_perf_sum %>% 
  filter(performance == "leaflength" | performance == "numleaves") %>% 
  ggplot(aes(x = year_f, y = mean)) +
  geom_col(aes(fill = soil), colour = "black",
           position = position_dodge2(preserve = "single")) +
  facet_wrap(~performance,
             labeller = as_labeller(c("leaflength" = "Mean leaf length (cm)",
                                      "numleaves" = "Mean number of leaves")),
             scales = "free_y",
             strip.position = "left") +
  geom_errorbar(aes(x = year_f, ymin = ifelse(mean - se < 0, 0, mean - se), ymax = mean + se),
                position = position_dodge2(preserve = "single", padding = 0.5),
                colour = "black") +
  scale_x_discrete(name = "Year",
                   labels = c("2021", "2022", "2023", "2024")) +
  scale_y_continuous(name = NULL,
                     limits = c(-0.01, NA), expand = expansion(mult = c(0, 0.2))) + 
  scale_fill_brewer(name = "Soil Origin",
                    palette = "BrBG", direction = 1,
                    labels = c("Dump", "Tundra (Control)")) +
  geom_text(data = emm_df,
            aes(y = mean + se, label = group,
                vjust = -1),
            position = position_dodge2(width = 0.9)) +
  theme_vz() +
  # theme_darkclassic() +
  theme(strip.background = element_blank(),
        strip.placement = "outside",
        legend.position = "none")

# ggsave(here::here("4.1_Soil_Origin/plots/fig_toffperf.png"), fig_toffperf,
# width = 12, height = 7)
```


## Combined Figures

Performance
```{r}
fig_sppperf <- fig_lvulperf +
  fig_pmajperf +
  fig_toffperf +
  plot_layout(guides = "collect", nrow = 3) +
  plot_annotation(tag_levels = c("A", "B", "C")) & 
  theme(legend.position = "right")
```

# Flowering

```{r number of flowering plants}
flower_sum <- df_performance %>% 
  filter(performance == "numflower") %>% 
  group_by(soil, species, year) %>% 
  dplyr::summarise(total = sum(values, na.rm = TRUE))

flower_sum
```

```{r number of flowering plants plot}
flower_sum %>% 
  ggplot(aes(x = soil, y = total, fill = soil)) +
  facet_wrap(~species) +
  geom_col() +
  theme_vz()
```

# EXTRAS

```{r model assumptions}
# par(mfrow = c(2, 2))
# plot(model)
```
